services:
  postgres:
    image: postgres:15-alpine
    container_name: sec-com-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE:-sec_com_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: sec-com-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-sec_com_db}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-your-email@gmail.com}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-your-app-password}
      MAIL_FROM: ${MAIL_FROM:-your-email@gmail.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-SEC - Cuộc thi Bản lĩnh Nhà đầu tư}
      APP_URL: ${APP_URL:-https://seccom.com}
      FRONTEND_URL: ${FRONTEND_URL:-*}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-15m}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-7d}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-name}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-key}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-secret}
    ports:
      - "3000:3000"
    command: ["node", "dist/main.js"]

volumes:
  pgdata: